# Generates Global/GitVersion.h (branch, commit, repository URL) from the git
# checkout being built, so `Natron --version`, the About window and saved
# projects name the exact build. Run as a script:
#   cmake -DSOURCE_DIR=<repo> -DOUTPUT_DIR=<dir> -P Global/GitVersion.cmake
# It writes <OUTPUT_DIR>/Global/GitVersion.h, and only touches the file when
# the values changed, so incremental builds don't recompile for nothing.
# NATRON_GIT_COMMIT / NATRON_GIT_BRANCH / NATRON_GIT_URL in the environment
# override git (CI passes them from its own metadata). Without git (source
# tarball), an existing header is kept, else the tracked placeholder is copied.

set(out "${OUTPUT_DIR}/Global/GitVersion.h")
set(placeholder "${SOURCE_DIR}/Global/GitVersion.h")

find_package(Git QUIET)

set(commit "$ENV{NATRON_GIT_COMMIT}")
set(branch "$ENV{NATRON_GIT_BRANCH}")
set(url "$ENV{NATRON_GIT_URL}")
if(commit)
    if(NOT branch)
        set(branch "detached")
    endif()
elseif(GIT_EXECUTABLE)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse HEAD
                    OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE
                    ERROR_QUIET RESULT_VARIABLE rc)
    if(NOT rc EQUAL 0)
        set(commit "")
    endif()
endif()

if(commit AND NOT branch)
    # Branch: the checked-out one, or in a detached checkout (CI) the branch
    # whose tip this commit is (actions/checkout leaves origin/<branch> in place).
    if(DEFINED ENV{GITHUB_REF_NAME} AND NOT "$ENV{GITHUB_REF_NAME}" STREQUAL "")
        set(branch "$ENV{GITHUB_REF_NAME}")
    else()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --abbrev-ref HEAD
                        OUTPUT_VARIABLE branch OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(branch STREQUAL "HEAD" OR branch STREQUAL "")
            # Default output is "<sha> commit<TAB><refname>" per line; no --format,
            # since its %(...) placeholders don't survive execute_process on Windows.
            execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" for-each-ref
                                    --points-at HEAD refs/heads refs/remotes
                            OUTPUT_VARIABLE refs ERROR_QUIET)
            set(branch "detached")
            string(REGEX MATCHALL "refs/(heads|remotes/[^/\n]+)/[^\n]+" refs "${refs}")
            foreach(ref IN LISTS refs)
                string(REGEX REPLACE "^refs/(heads|remotes/[^/]+)/" "" ref "${ref}")
                string(STRIP "${ref}" ref)
                if(NOT ref STREQUAL "HEAD" AND NOT ref STREQUAL "")
                    set(branch "${ref}")
                    break()
                endif()
            endforeach()
        endif()
    endif()

endif()

if(commit AND NOT url AND GIT_EXECUTABLE)
    # Repository URL for the About-window links: origin, normalised to https.
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" remote get-url origin
                    OUTPUT_VARIABLE url OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    string(REGEX REPLACE "^git@github\.com:" "https://github.com/" url "${url}")
    string(REGEX REPLACE "\.git$" "" url "${url}")
    if(NOT url MATCHES "^https?://")
        set(url "")
    endif()
endif()

if(NOT url)
    set(url "https://github.com/NatronGitHub/Natron")
endif()

if(NOT commit AND EXISTS "${out}")
    # No git here (e.g. the build-time refresh in a stripped container):
    # keep whatever configure generated rather than regress to the placeholder.
    return()
endif()

if(commit)
    set(content "#ifndef NATRON_GITVERSION_H_
#define NATRON_GITVERSION_H_
/* Generated by Global/GitVersion.cmake; do not edit. */
#define GIT_BRANCH \"${branch}\"
#define GIT_COMMIT \"${commit}\"
#define NATRON_GIT_URL \"${url}\"
#define IO_GIT_COMMIT \"\"
#define MISC_GIT_COMMIT \"\"
#define ARENA_GIT_COMMIT \"\"
#define GMIC_GIT_COMMIT \"\"
#endif
")
else()
    file(READ "${placeholder}" content)
endif()

set(existing "")
if(EXISTS "${out}")
    file(READ "${out}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${out}" "${content}")
    if(commit)
        message(STATUS "GitVersion.h: ${branch} ${commit}")
    else()
        message(STATUS "GitVersion.h: no git checkout, using the placeholder")
    endif()
endif()
